steps:
# Build and push the gateway image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/gateway:latest', './gateway']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/gateway:latest']

# Build and push the user-service image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/user-service:latest', './user-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/user-service:latest']

# Build and push the seller-service image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/seller-service:latest', './seller-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/seller-service:latest']

# Build and push the order-service image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/order-service:latest', './order-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/order-service:latest']

# Build and push the admin-service image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/admin-service:latest', './admin-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/admin-service:latest']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/gateway:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/user-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/seller-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/order-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/lonar-repo/admin-service:latest'
