apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/your-gcp-project-id/user-service:v1 # Replace with your image
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-service
  labels:
    app: seller-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller-service
  template:
    metadata:
      labels:
        app: seller-service
    spec:
      containers:
      - name: seller-service
        image: gcr.io/your-gcp-project-id/seller-service:v1 # Replace with your image
        ports:
        - containerPort: 8003

---

apiVersion: v1
kind: Service
metadata:
  name: seller-service
spec:
  selector:
    app: seller-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gcr.io/your-gcp-project-id/order-service:v1 # Replace with your image
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: gcr.io/your-gcp-project-id/admin-service:v1 # Replace with your image
        ports:
        - containerPort: 8004

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gcr.io/your-gcp-project-id/gateway:v1 # Replace with your image
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
