apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: gcr.io/YOUR_PROJECT_ID/admin-service:latest
        ports:
        - containerPort: 8004
        envFrom:
        - secretRef:
            name: microservice-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
