apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gcr.io/YOUR_PROJECT_ID/gateway:latest # This will be replaced by Cloud Build
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: microservice-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer # Exposes this service to the internet
