apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller-service
  template:
    metadata:
      labels:
        app: seller-service
    spec:
      containers:
      - name: seller-service
        image: gcr.io/YOUR_PROJECT_ID/seller-service:latest
        ports:
        - containerPort: 8003
        envFrom:
        - secretRef:
            name: microservice-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: seller-service
spec:
  selector:
    app: seller-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
